// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBICKUO7X6iNEy7Np3a-pNqU5uW7xSK9w',
    appId: '1:747009347671:web:e3804be6527e4520afd312',
    messagingSenderId: '747009347671',
    projectId: 'poland-quiz-62dae',
    authDomain: 'poland-quiz-62dae.firebaseapp.com',
    storageBucket: 'poland-quiz-62dae.appspot.com',
    measurementId: 'G-6QYXNWSQN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQSWhX2Js0NbZZoINbE2Pxdfwe-79QiOQ',
    appId: '1:747009347671:android:24a0f0fbfaab90cbafd312',
    messagingSenderId: '747009347671',
    projectId: 'poland-quiz-62dae',
    storageBucket: 'poland-quiz-62dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoxoTUCE5djTRo3Y_Mk1HH99qwDobp9sg',
    appId: '1:747009347671:ios:406cf46bbf46785aafd312',
    messagingSenderId: '747009347671',
    projectId: 'poland-quiz-62dae',
    storageBucket: 'poland-quiz-62dae.appspot.com',
    iosClientId: '747009347671-fbmdvs4di8dh72qmcfu1cn4i2hgdmoj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.polandQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoxoTUCE5djTRo3Y_Mk1HH99qwDobp9sg',
    appId: '1:747009347671:ios:406cf46bbf46785aafd312',
    messagingSenderId: '747009347671',
    projectId: 'poland-quiz-62dae',
    storageBucket: 'poland-quiz-62dae.appspot.com',
    iosClientId: '747009347671-fbmdvs4di8dh72qmcfu1cn4i2hgdmoj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.polandQuiz',
  );
}
